### ISSUE TITLE
mechanism to encourage ratings/reviews

### ISSUE THREAD

**Issue by bryndyment** [hoologic/app.realkana#1]
ideas? let's discuss

**Comment by seancoady** [comment]
Just committed some changes for this. Give it a try. The text, timing, rules, and placement should be fairly configurable. I'd recommend testing this in RealKana, and it must be tested on a device, not in the Simulator.

**Comment by bryndyment** [comment]
Let's do this:

- `Rate` button appears bottom-right (same style/width/positioning as `Settings` but bottom-right)
- tap `Rate` and a standard confirmation comes up: `Rate Real Kana in the App Store?` (w. `OK` and `Cancel`)

`Rate` button only appears when:

1. in keyboard or swipe mode, and
2. user gets 100% correct, and
3. user gets at least `15 | 15`, and
4. one-in-ten chance after all above is met

Goes away forever if user hits `OK` twice or `Cancel` three times.  (This resets when app updates.)

Sound OK?

**Comment by seancoady** [comment]
"Goes away forever if user hits OK twice or Cancel three times."

This seems weird. If the user taps OK, it will take them to the AppStore
right? I don't think we should prompt them again once they've tapped OK.
The Cancel three times thing probably isn't necessary given the extremely
small chance of the button being shown.

Does the Rate button only appear on the end of set summary view?

The sets in RealKanji are huge, so after completing a single set of 100
kanji, getting 100% right, there's still only a 10% chance of seeing the
button? And that's assuming you only have one set checked. At that rate,
you'll never see the button.

**Comment by bryndyment** [comment]
Updated my comments.

Rate button (conditionally) appears on swiping back as well.

The button can theoretically show up a fair number of times for Real Kana users, and I don't want it to be an annoyance, so let's suppress forever after two cancels.

**Comment by seancoady** [comment]
How about Continuous Mode? Do you still want to show it on swipe back? If so that would mean you'd stop showing it if the user made a single mistake in RealKana (to meet the 100% correct requirement).

For RealKanji, what does it mean to require 15 | 15, but 90% is still OK?

**Comment by bryndyment** [comment]
Continuous mode ... yes, show it.  And, yes, as soon as a mistake's made (on Real Kana), that's it.

For 15 | 15, let's change the rule to:

- at least 15 cards shown
- 100% right for Real Kana, 90+% right for Real Kanji

**Comment by bryndyment** [comment]
You're not putting spaces between Real Kana and Real Kanji to mess with me, right?

**Comment by seancoady** [comment]
"Rate Real Kana in the App Store?" with "Cancel"/"OK" is pretty boring. What about "No, Thanks"/"Sure"

**Comment by bryndyment** [comment]
Nah | OK!

**Comment by bryndyment** [comment]
commit 623acff94285d548bedcb5aac1ad2a84a9f817a3
Author: Bryn Dyment <bryn@hoologic.com>
Date:   Mon Feb 16 19:04:43 2015 +0900

    kana/kanji/math - updated rating labels

**Comment by bryndyment** [comment]
close out if looks good

**Comment by bryndyment** [comment]
![img_9987](https://cloud.githubusercontent.com/assets/7953560/6211645/a797ad3e-b61f-11e4-81b6-e5283bef0eee.PNG)

**Comment by seancoady** [comment]
looks good, nice touch!
