### ISSUE TITLE
better reveal when tapping on help text heading

### ISSUE THREAD

**Issue by bryndyment** [hoologic/app.realkana#11]
When tapping on a help text heading, can we

- immediately hide the currently-opened one
- reveal via "rolling down" the help text rather than showing it all at once

?

**Comment by bryndyment** [comment]
Can look a bit weird with both transitions happening at once.  Can you immediately hide the currently-opened one and only transition the new one?

**Comment by seancoady** [comment]
it looks like you can't mix and match animations like that in a table view. All the cells need to be inserted/deleted simultaneously.

**Comment by bryndyment** [comment]
let's switch back to how it was, then

**Comment by seancoady** [comment]
leaving as is per our chat. Also added the fix to keep the tapped section from scrolling off screen.

**Comment by bryndyment** [comment]
:+1:
