### ISSUE TITLE
"Rate" button logic change

### ISSUE THREAD

**Issue by bryndyment** [hoologic/app.realkana#12]
I was playing around with the `Rate` button and think the logic is kinda complicated and unnecessary.  Let's do the following instead ... less need for keeping state/count.

For every time the score page is shown (regardless of how user got there ... swipe back vs. end-of-session):
- `if` score is at least 90% (all three apps)
- `and` number correct is at least 15 (i.e., first number in score is 15+)
- `10% chance` that `Rate` is shown

Always suppress rate button if:
- `いいえ` has been tapped twice, `or`
- `はい` has been tapped once

Reset with each new version.

**Comment by seancoady** [comment]
Please confirm:
• are we including the Rate button in slideshow mode too? It was previously excluded (i.e. "in keyboard or swipe mode (incl. continuous mode)")
• the number correct is reset every time you drop out of settings and start a new sequence. For the purpose of meeting a minimum correct count, we want to compare against the fresh number in this case right? i.e. not some cumulative app count?

**Comment by bryndyment** [comment]
no slideshow mode

compare against fresh number ... no cumulative

**Comment by seancoady** [comment]
good, that's how the latest build is set up.

**Comment by bryndyment** [comment]
feels right :+1:
