### ISSUE TITLE
"swipe right to access settings" hint

### ISSUE THREAD

**Issue by bryndyment** [hoologic/app.realkana#2]
`Swipe right to access score and settings.` (Real Kana, Real Kanji iPad)

`Swipe down to access score and settings.` (Real Kanji iPhone)

**Comment by bryndyment** [comment]
Let's do this:

- add a narrow, translucent band below the current band
- height and background/text colour of new band should match `Settings` button
- space between bands should match the space between `Settings` button and top of screen (don't change positioning of existing band)
- `Swipe right to access score and settings.`

This remains in place until user swipes right.  After swiping right, band is still there, with the following text:

- `Swipe left to return.`

After returning and transition has stopped, the band fades, never to be seen again.

What do you think?

**Comment by seancoady** [comment]
I think that'll work. So the width of the band is the entire span of the page?

Want to use an effect like this? https://github.com/facebook/Shimmer

**Comment by bryndyment** [comment]
Yes, spans entire page.

Shimmer :-1:  :smiley:

**Comment by seancoady** [comment]
how do you want to display the hint in these modes:
1) Real Kanji iPhone landscape keyboard mode, where we show the white stripe covering the whole screen above the keyboard
2) Real Kanji/Real Kana, vertical text, where the white stripe runs top to bottom

**Comment by bryndyment** [comment]
1. only show the hint in swipe mode, which will be default mode for both Real Kana and Real Kanji
2. only show hint for horizontal text

**Comment by bryndyment** [comment]
- suppress hint entirely in Real Kanji
- show "swipe right" message above (and touching) white band, not below
- show "swipe left" message below (and touching) white band
- suppress all interaction (e.g., advancing, double-tap) until user swipes right
- once user has swiped right, either swiping left or hitting settings will "unlock" interaction

**Comment by bryndyment** [comment]
How does this sound?

- suppress hint entirely in vertical text mode
- suppress hint entirely in non-swipe mode
- initial state: band above white band with `Swipe forward to see next character.`
- initial state: band below white band with `Swipe back to see score and settings.`
- top band disappears as soon as user swipes forward (fades out after arrival)
- bottom band disappears as soon as user swipes back (fades out after arrival)

Bands should be same style as now, except with no gap between them and the white band.

**Comment by seancoady** [comment]
Just read your latest updates, so my latest commit won't be 100% what you're asking for but give it a try. Why the "being in vertical text mode (even if that's the app's initial state)" rule? That means Real Kanji users would never see it?

**Comment by bryndyment** [comment]
Real Kanji iPad users'll see it, but I think it's a non-issue anyway as so many of Real Kanji sales are either via the bundle or (assuming) from Real Kana users anyway.

Hint text would look bad vertically.

"Swipe forward" and "Swipe back" are clear and unambiguous but I don't think "Swipe down" and "Swipe up" are.

Just not worth it overall!

**Comment by seancoady** [comment]
The way I have it working now (prior to reading your email) is that it will show in Real Kanji in landscape mode. When you rotate to portrait it disappears, and if you rotate back to landscape it re-appears. The only way to dismiss the hints is by swiping forward and back. So Real Kanji iPad will be the same as Math and Real Kana, and Real Kanji iPhone will be the same as long as you're holding the iPhone in landscape mode. Sound good?

**Comment by bryndyment** [comment]
No, I don't like the idea of the hint not being there, then appearing when you rotate to horizontal text.

I want the hint text to only ever be there on first launch.

**Comment by seancoady** [comment]
how about the wording of this string for the three apps: "Swipe forward to see next character"

Real Kana = "next character"
Real Kanji = "next word"
Math = "next question"

?

**Comment by seancoady** [comment]
Give it a try. Going back over the notes from this thread, I think everything is captured except for one point: disabling functionality until the swipe action is performed. I wanted to give you a chance to play with it first before I go ahead with that rule. Does it make sense to show the swipe left hint if we're disabling it until the swipe right first? Seems a little weird if we do.

**Comment by bryndyment** [comment]
(closing this off and will open single-issue bug reports)
