### ISSUE TITLE
send me your public key

### ISSUE THREAD

**Issue by bryndyment** [hoologic/app.realkana#6]
`~/.ssh/id_rsa.pub`

**Comment by seancoady** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAsABn0CCOs7FA4RHivvjN9Bp7/n6Ydp6ZQXpu83fe4AGAfnJOSaxGSEKGssDTS6IX8Q/XEhNzxYe3bTFBdIzldy1/M+BuXjp5dVpUzMa+jbdlEps/iqeoSiyYYEomKji9bJyr5PF4IGbijUO/8bEM7E88IPCcwSFMemYzGHD2DKMNSISbCkM2FvPX0fNWgjAMSAJgG5fRq28iD5P8dmhk0rr2EFM2KRYaO5WPAYIiQJZHosxSDm21MdEXlSVoQYN2g84L8HAdKFTmK5KT554GVc3evY7gQHITUslXJf8LwhgaREX/IlTaeoblXyFGL+lZwjNuz+gcH/d/Koudt42ZjQ== seancoady@SEAN-COADYs-iMac.local

**Comment by bryndyment** [comment]
`git clone git@hoologic.com:app.realkana`

We will use the above repo for code and `github.com/hoologic/app.realkana` just for issues.  Tricky, eh?

**Comment by seancoady** [comment]
I'm in
