### ISSUE TITLE
swap positions of "swipe forward" and "swipe back" hints

### ISSUE THREAD

**Issue by bryndyment** [hoologic/app.realkana#9]
"swipe forward" should be above the white bar

"swipe back" should be below the white bar

**Comment by bryndyment** [comment]
commit 07ca76f77551f44d2e51a95e41e39fa8484cfdf6
Author: Bryn Dyment <bryn@hoologic.com>
Date:   Mon Feb 16 09:41:41 2015 +0900

    #9 - swap hint positions

**Comment by seancoady** [comment]
Looks good! :ship:
